server:
  port: 8080

spring:
  application:
    name: tv-middleware
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/tv_middleware}
      auto-index-creation: true

tvmaze:
  base-url: https://api.tvmaze.com
